[package]
name = "try-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
bb8 = "0.8"
bb8-postgres = "0.8"
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-postgres = "0.7"
